InnovationGame/InnovationGame/Models/Code.cs
using Dapper.Contrib.Extensions;

namespace InnovationGame.Models
{
    [Table("ambev.Code")]
    public class Code
    {
        [ExplicitKey]
        public string CodeId { get; set; }
        public int ProdutoId { get; set; }
        public int InfluenciadorId { get; set; }
    }
}

InnovationGame/InnovationGame/Models/Compra.cs
using Dapper.Contrib.Extensions;
using System;

namespace InnovationGame.ViewModels
{
    [Table("ambev.Compra")]
    public class Compra
    {
        [Key]
        public int CompraId { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string CEP { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public string CartaoCredito { get; set; }
        public string NomeCartao { get; set; }
        public string CartaoVencimento { get; set; }
        public string CartaoCVV { get; set; }
        public string Celular { get; set; }
        public string CodeId { get; set; }
        public DateTime Timestamp { get; set; }
    }
}

InnovationGame/InnovationGame/Models/CompraProduto.cs
using Dapper.Contrib.Extensions;

namespace InnovationGame.Models
{
    [Table("ambev.CompraProduto")]
    public class CompraProduto
    {
        [ExplicitKey]
        public int CompraId { get; set; }
        public int ProdutoId { get; set; }
        public int Quantidade { get; set; }
    }
}

InnovationGame/InnovationGame/Models/ErrorViewModel.cs
using System;

namespace InnovationGame.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InnovationGame/InnovationGame/Models/Influenciador.cs
using Dapper.Contrib.Extensions;

namespace InnovationGame.Models
{
    [Table("ambev.Influenciador")]
    public class Influenciador
    {
        [ExplicitKey]
        public int InfluenciadorId { get; set; }
        public string Nome { get; set; }
    }

}

InnovationGame/InnovationGame/Models/ProdutoModel.cs
using Dapper.Contrib.Extensions;

namespace InnovationGame.ViewModels
{
    [Table("ambev.Produtos")]
    public class ProdutoModel
    {
        [ExplicitKey]
        public int ProdutoId { get; set; }
        public string Nome { get; set; }
        public string Foto { get; set; }
        public double Preco { get; set; }
    }
}

InnovationGame/InnovationGame/ViewModels/CarrinhoViewModel.cs
namespace InnovationGame.ViewModels
{
    public class CarrinhoViewModel
    {
        public int Id { get; set; }
        public ProdutoViewModel Produto { get; set; }
        public int Quantidade { get; set; }
        public string Endereco { get; set; }
        public string NumeroCartao { get; set; }
        public string DataValidade { get; set; }
        public string CVV { get; set; }
    }
}

InnovationGame/InnovationGame/ViewModels/ProdutoViewModel.cs
using Dapper.Contrib.Extensions;
using System;

namespace InnovationGame.ViewModels
{
    [System.ComponentModel.DataAnnotations.Schema.Table("ambev.Produtos")]
    public class ProdutoViewModel
    {
        [ExplicitKey]
        public int ProdutoId { get; set; }
        public string Nome { get; set; }
        public string Foto { get; set; }
        public double Preco { get; set; }
    }
}

InnovationGame/InnovationGame/Controllers/CarrinhoController.cs
using InnovationGame.Service.Interfaces;
using InnovationGame.Servico.Interfaces;
using InnovationGame.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;

namespace InnovationGame.Controllers
{
    public class CarrinhoController : Controller
    {
        private readonly IProdutoServico _produtoServico;
        private readonly ICodeServico _codeServico;
        private readonly ICarrinhoServico _carrinhoServico;

        public CarrinhoController(IProdutoServico produtoServico, ICodeServico codeServico, ICarrinhoServico carrinhoServico)
        {
            _produtoServico = produtoServico;
            _codeServico = codeServico;
            _carrinhoServico = carrinhoServico;
        }

        public IActionResult Index()
        {

            try {
                string codeId = Request.Query["CodeId"];

                var code = _codeServico.ObterPorId(codeId);
                var produto = _produtoServico.ObterPorId(code.ProdutoId);

                ViewData["ProdutoNome"] = produto.Nome;
                ViewData["ProdutoFoto"] = produto.Foto;
                ViewData["ProdutoPreco"] = produto.Preco;
                ViewData["CodeId"] = code.CodeId;

            } catch (Exception e)
            {
                // ??
            }
            return View();
        }

        [HttpPost]
        public IActionResult ConfirmarCompra(Compra model)
        {
            model.Timestamp = DateTime.Now;

            try
            {
                _carrinhoServico.Salvar(model);
                return View("/Views/Carrinho/PedidoConfirmado.cshtml");
            }
            catch (Exception ex)
            {
                return new JsonResult(ex.Message);
            }
        }
    }
}

InnovationGame/InnovationGame/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using InnovationGame.Models;

namespace InnovationGame.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InnovationGame/InnovationGame/Controllers/ProdutoController.cs
using InnovationGame.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;

namespace InnovationGame.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly IProdutoServico _produtoServico;
        public ProdutoController(IProdutoServico produtoServico)
        {
            _produtoServico = produtoServico;
        }

        public IActionResult Index([FromRoute] int produtoId)
        {
            return View();
        }

        [HttpGet]
        public IActionResult ObterTodos()
        {
            try
            {
                var listaProdutos = _produtoServico.ObterTodos();
                return new JsonResult(listaProdutos);
            }
            catch (Exception ex)
            {
                return new JsonResult(ex.Message);
            }

        }

        [HttpGet]
        public IActionResult ObterPorId(int produtoId)
        {
            try
            {
                var produto = _produtoServico.ObterPorId(produtoId);
                return new JsonResult(produto);
            }
            catch (Exception ex)
            {
                return new JsonResult(ex.Message);
            }

        }
    }
}

InnovationGame/InnovationGame/Views/Carrinho/Detalhes.cshtml
@model InnovationGame.ViewModels.Compra
@{
    ViewData["Title"] = "Confirmação";
}
<html>
    <head>
        <style>
            .actions {
                display: flex;
                justify-content: flex-end;
            }
            .bold {
                font-weight: bold;
            }
            .corBotao {
                background-color: #6342a6;
                color: white;
                border-color: #6342a6;
            }
        </style>
    </head>

    <body>
        <div class="container mt-5">
            <h4>Dados da compra:</h4>

            <div class="mb-4">
                <div class="text-center mt-3">
                    <img src="https://www.confianca.com.br/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/r/e/refrigerante-guarana-antarctica-lata-350ml_1.jpg" width="200" height="200" />
                </div>
                <div class="text-center">
                    <label>Descrevendo o produto aqui</label>
                </div>
                <div class="text-center">
                    <label>Quant: 1</label>
                </div>
                <div class="text-center">
                    <label>5,99</label>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label class="bold">Celular: </label>
                    <span>(16) 99999-9999</span>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label class="bold">Endereço: </label>
                    <span>Teste Teste Teste</span>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label class="bold">Cep: </label>
                    <span>Teste Teste Teste</span>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label class="bold">Estado: </label>
                    <span>Teste Teste Teste</span>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label class="bold">Cidade: </label>
                    <span>Teste Teste Teste</span>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label class="bold">Número: </label>
                    <span>1</span>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label class="bold">Nome: </label>
                    <span>Teste Teste Teste</span>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label class="bold">Cartão: </label>
                    <span>123456789123</span>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label class="bold">Validade: </label>
                    <span>10/2022</span>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <label class="bold">CVV: </label>
                    <span>123</span>
                </div>
            </div>
        </div>

        <div class="mt-5 mb-5 actions">
            <button id="voltar" class="btn btn-light btn-lg mr-2" onclick="">Voltar</button>
            <button id="submit" class="btn corBotao btn-lg" onclick="salvar()">Confirmar</button>
        </div>
    </body>
</html>

<script type="text/javascript">

    function salvar() {
        var carrinho = mapearObjetoParaSalvar();
        $.ajax({
            type: "POST",
            url: '@Url.Action("ConfirmarCompra", "Carrinho")',
            data: JSON.stringify(carrinho),
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function () {
                alert("Data has been added successfully.");
            },
            error: function () {
                alert("Error while inserting data");
            }
        });
    }

    function mapearObjetoParaSalvar() {
        var carrinho = {};
        return carrinho;
    }

</script>

InnovationGame/InnovationGame/Views/Carrinho/PedidoConfirmado.cshtml
@{
    ViewData["Title"] = "PedidoConfirmado";
}
<html>
    <head>
        <style>
            .actions {
                display: flex;
                justify-content: flex-end;
            }
            .margemAcima {
                margin-top: 100px;
            }
        </style>
    </head>

    <body>
        <div class="container margemAcima">
            <div style="font-size: 80px;" class="text-center">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check2-square" fill="#7CFC00" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M15.354 2.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L8 9.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
                    <path fill-rule="evenodd" d="M1.5 13A1.5 1.5 0 0 0 3 14.5h10a1.5 1.5 0 0 0 1.5-1.5V8a.5.5 0 0 0-1 0v5a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V3a.5.5 0 0 1 .5-.5h8a.5.5 0 0 0 0-1H3A1.5 1.5 0 0 0 1.5 3v10z" />
                </svg>
            </div>

            <div class="text-center">
                <h3>Pedido realizado com sucesso!</h3>
            </div>
            <div class="text-center">
                <label>Seu pedido foi enviado para o Zé Delivery basta aguardar a entrega</label>
            </div>      
        </div>
    </body>
</html>

InnovationGame/InnovationGame/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

InnovationGame/InnovationGame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NABoa</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js"></script>
    <style>
        .alinharCentro {
            display: flex;
            align-items: center;
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow" style="background-color:#ccc">
            <div class="container">
                <div class="alinharCentro">
                    <div style="font-size: 20px">
                        <img style="width: 50%; margin-left:80px;" src="https://cdn.discordapp.com/attachments/741344471878336545/744381842244894822/Picture1.png" />
                    </div>
                    @*<div class="ml-3">
                            <a  style="color: #6342a6;font-size: 35px;font-weight: bold;margin-top: 4px;" class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">nab<label style="color:black">oa</label></a>
                        </div>*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color: #212529;" class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - NABoa
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>